# Generated by Django 2.0.9 on 2018-12-16 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEquipe', models.CharField(max_length=100, verbose_name="Nom de l'équipe")),
                ('nomContact', models.CharField(max_length=100, verbose_name='Nom du contact')),
                ('prenomContact', models.CharField(max_length=100, verbose_name='Prénom du contact')),
                ('emailContact', models.CharField(max_length=100, verbose_name='Courriel du contact')),
                ('telephoneContact', models.CharField(max_length=10, verbose_name='Téléphone du contact')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Equipe',
            },
        ),
    ]
